name: Publish Docker image

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    name: ${{ matrix.IMAGES }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        IMAGES: [nginx, hentaiathome, bun]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: qemu
        uses: docker/setup-qemu-action@v2

      - name: buildx
        uses: docker/setup-buildx-action@v2

      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.IMAGES }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.IMAGES }}-buildx

      - name: build
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ${{ matrix.IMAGES }}
          tags: ghcr.io/${{ github.actor }}/${{ matrix.IMAGES }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: cache-modding
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
