name: Publish Docker image

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    name: ${{ matrix.IMAGES }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        IMAGES: [nginx, hentaiathome, bun, ga-runner-node]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: qemu
        uses: docker/setup-qemu-action@v2

      - name: buildx
        uses: docker/setup-buildx-action@v2

      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ${{ matrix.IMAGES }}
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.actor }}/${{ matrix.IMAGES }}:latest
